apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporary-rbac-controller
  namespace: temporary-rbac-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporary-rbac-controller
  template:
    metadata:
      labels:
        app: temporary-rbac-controller
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      serviceAccountName: temporary-rbac-controller-sa
      containers:
        - name: controller
          image: docker.io/guybalmas/temporary-rbac-controller:v1.0.36
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - "--enable-leader-election=false"
          resources:
            limits:
              memory: 64Mi
              cpu: 50m
            requests:
              memory: 32Mi
              cpu: 20m
