apiVersion: tarbac.io/v1
kind: ClusterSudoPolicy
metadata:
  name: self-service-selected-namespaces-admin
spec:
  maxDuration: 4h
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  allowedUsers:
    - name: i-hate-life
  allowedNamespacesSelector:
    matchLabels:
      team: a