apiVersion: tarbac.io/v1
kind: ClusterSudoPolicy
metadata:
  name: self-service-dev-admin
spec:
  maxDuration: 4h
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  allowedUsers:
    - name: masterclient
  allowedNamespaces:
    - default
    - dev